sudo: required

language: php

services:
- docker

script:
- docker build -t amixsi/php-box:latest .

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push amixsi/php-box
  fi